package provenance

import "time"

// SourceType identifies what created or modified an engram.
type SourceType uint8

const (
	SourceHuman      SourceType = 1 // written by a human user
	SourceLLM        SourceType = 2 // generated by an LLM (e.g. enrichment worker)
	SourceDocument   SourceType = 3 // extracted from a document
	SourceInferred   SourceType = 4 // inferred by the system (e.g. relevance update)
	SourceExternal   SourceType = 5 // imported from external system
	SourceWorkingMem SourceType = 6 // promoted from working memory
	SourceSynthetic  SourceType = 7 // created by consolidation worker
)

// ProvenanceEntry records a single create/update event on an engram.
type ProvenanceEntry struct {
	Timestamp time.Time
	Source    SourceType
	AgentID   string // e.g. "user:mj", "ollama:llama3.2", "consolidation-worker"
	Operation string // "create", "update-relevance", "update-meta", "merge", "promote"
	Note      string // optional free text
}
