package replication

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"
)

var ErrTokenExpired = errors.New("join token: expired")
var ErrTokenInvalid = errors.New("join token: invalid")

// JoinTokenManager generates and validates time-limited join tokens.
// Token format: "<issuedUnixNano>.<nonce16hex>.<hmac-sha256-hex>"
// When clusterSecret is empty, token validation is skipped (open cluster).
type JoinTokenManager struct {
	secret []byte
	ttl    time.Duration
}

// NewJoinTokenManager returns a JoinTokenManager configured with the given
// cluster secret and token TTL. When clusterSecret is empty the cluster is
// considered open: tokens are random hex values and Validate only checks that
// the token is non-empty.
func NewJoinTokenManager(clusterSecret string, ttl time.Duration) *JoinTokenManager {
	return &JoinTokenManager{secret: []byte(clusterSecret), ttl: ttl}
}

// Generate creates a new join token valid for ttl duration.
func (m *JoinTokenManager) Generate() (string, error) {
	if len(m.secret) == 0 {
		b := make([]byte, 16)
		if _, err := rand.Read(b); err != nil {
			return "", fmt.Errorf("jointoken: rand: %w", err)
		}
		return hex.EncodeToString(b), nil
	}
	now := strconv.FormatInt(time.Now().UnixNano(), 10)
	nonce := make([]byte, 8)
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("jointoken: rand nonce: %w", err)
	}
	nonceHex := hex.EncodeToString(nonce)
	mac := hmac.New(sha256.New, m.secret)
	mac.Write([]byte(now + "." + nonceHex))
	sig := hex.EncodeToString(mac.Sum(nil))
	return now + "." + nonceHex + "." + sig, nil
}

// Validate checks that tok was generated by this manager and has not expired.
func (m *JoinTokenManager) Validate(tok string) error {
	if len(m.secret) == 0 {
		if tok == "" {
			return ErrTokenInvalid
		}
		return nil
	}
	parts := strings.SplitN(tok, ".", 3)
	if len(parts) != 3 {
		return ErrTokenInvalid
	}
	nanos, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return ErrTokenInvalid
	}
	issued := time.Unix(0, nanos)
	now := time.Now()
	// Reject tokens from the future (clock skew tolerance: 5s)
	if issued.After(now.Add(5 * time.Second)) {
		return ErrTokenInvalid
	}
	// Reject expired tokens
	if now.Sub(issued) > m.ttl {
		return ErrTokenExpired
	}
	// Verify nonce is valid hex (16 chars = 8 bytes)
	if len(parts[1]) != 16 {
		return ErrTokenInvalid
	}
	// Recompute MAC over "<nanos>.<nonce>"
	mac := hmac.New(sha256.New, m.secret)
	mac.Write([]byte(parts[0] + "." + parts[1]))
	expected := hex.EncodeToString(mac.Sum(nil))
	// hmac.Equal is safe here: both expected and parts[2] are hex-encoded
	// SHA-256 output, so they are always 64 chars if valid.
	if !hmac.Equal([]byte(parts[2]), []byte(expected)) {
		return ErrTokenInvalid
	}
	return nil
}

// TTL returns the configured token lifetime.
func (m *JoinTokenManager) TTL() time.Duration { return m.ttl }
